-- this file was generated using https://www.mockaroo.com/

insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Sarene Covendon', 1, 10);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Latrena Cowdery', 2, 1);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Everett Ashton', 2, 1);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Elora Vitall', 1, 4);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Rosette Arnholz', 1, 6);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Hyacinthia Tyrwhitt', 1, 9);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Joey Kibblewhite', 2, 5);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Electra Van Dalen', 1, 8);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Ethelbert Tolle', 2, 3);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Aurore Kearsley', 1, 2);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Fayette Halstead', 1, 4);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Briant Melpuss', 2, 3);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Harbert O''Scanlon', 1, 10);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Jerrilee Ealden', 2, 10);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Edgard Wagen', 1, 10);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Emmeline Whitely', 2, 4);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Amity Minshull', 1, 3);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Dorothee Ebbage', 2, 6);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Shelli Passmore', 2, 10);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Kelwin Arrandale', 2, 5);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Waring Chisolm', 1, 3);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Claudius Sherrum', 1, 3);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Sadie Gorrie', 1, 4);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Myrwyn Scrymgeour', 1, 5);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Peri King', 2, 1);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Doug Gascoyne', 1, 3);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Joey Edmondson', 1, 1);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Boone Brecknall', 2, 6);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Alikee Dennington', 1, 9);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Kinny Forrestor', 1, 7);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Kasper Eastes', 1, 5);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Sax Avey', 1, 9);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Bryna Hallifax', 2, 1);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Celie Rissen', 2, 6);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Kizzee Corrado', 2, 5);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Malinde La Rosa', 1, 8);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Gert Goley', 2, 10);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Nydia Purselow', 1, 6);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Connie Peploe', 2, 2);
insert into relational.dispatchers (name, id_status, id_subsidiary) values ('Stefano Barthelemy', 2, 6);